from __future__ import annotations

from typing import Protocol


class LedgerPort(Protocol):
    def list_holdings(self) -> list[dict]: ...
    def list_history(self) -> list[dict]: ...
    def create_purchase(self, **kwargs) -> dict: ...
    def record_sale(self, **kwargs) -> dict: ...
    def receive_pending_purchase(self, **kwargs) -> dict: ...
    def list_pending_purchases(self) -> list[dict]: ...
    def search_catalog(self, query: str, limit: int = 20) -> list[dict]: ...
